# Generated by Django 3.1.4 on 2021-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numClient', models.CharField(max_length=4)),
                ('numMat', models.CharField(max_length=4)),
                ('qte', models.IntegerField()),
                ('date_achat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numClient', models.CharField(max_length=4)),
                ('nomClient', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMat', models.CharField(max_length=4)),
                ('design', models.CharField(max_length=20)),
                ('Pu', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='imgMateriel')),
            ],
        ),
    ]
