# Generated by Django 3.1.4 on 2021-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetVrai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='image',
            field=models.ImageField(upload_to='ProjetVrai/ProjetVrai/ProjetVrai/imgMateriel'),
        ),
    ]
